name: Build Linux

on:
  push:
    branches:
    - main
    - dev
  pull_request:
    branches:
    - main
    - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Install dependencies
        run: dart pub get
      
      - name: Build Source
        run: dart compile exe bin/ultroid_cli.dart -DDEBUG=false -o build/ultroid

      - name: Upload UltrodiCli For Linux
        uses: actions/upload-artifact@v2.2.4
        with:
          name: ultorid
          path: build/ultroid
