name: Build MacOS

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    - dev

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Install dependencies
        run: dart pub get
      
      - name: Build Source
        run: dart compile exe bin/ultroid_cli.dart -DDEBUG=false -o ./ultroid-macos
        

      - name: Upload UltrodiCli For MacOS
        uses: actions/upload-artifact@v2.2.4
        with:
          name: ultroid-macos
          path: ultroid-macos
